name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Create necessary directories
      run: |
        mkdir -p data

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pyyaml tqdm dockerfile-parse
    
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Run scripts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
      run: |
        python parse_images.py
        python image_hierarchy.py
        python image_info.py
        python language_ident.py
        python syft_check.py
        python dependency_reader.py
        python stig_parser.py

    - name: Upload result file
      uses: actions/upload-artifact@v2
      with:
        name: used-stigs
        path: data/used_stigs.json

  create-pr-message:
    needs: build-and-run-scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: used-stigs
        path: data

    - name: Read json file
      id: read-file
      run: echo "::set-output name=content::$(cat data/used_stigs.json)"

    - name: Create Pull Request Message
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update STIGs"
        title: "Updated STIG Information"
        body: |
          ```json
          ${{ steps.read-file.outputs.content }}
          ```
        branch: update-stigs-${{ github.head_ref }}
        labels: update
        token: ${{ secrets.GITHUB_TOKEN }}
